{{- if and (.Values.auth.enabled) (not .Values.auth.existingDbSecret) (.Values.auth.additionalUsers) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "mongodb-replicaset.name" . }}
    chart: {{ template "mongodb-replicaset.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
  name: {{ template "mongodb-replicaset.dbSecret" . }}
type: Opaque
data:
{{- range $i, $users := .Values.auth.additionalUsers }}
  "user{{ add1 $i}}": {{ $users.username | b64enc }}
  "password{{ add1 $i}}": {{ $users.password | b64enc }}
{{- end -}}
{{- end -}}
